server:
  port: 8888

fb:
  page:
    token: ${USS_MESSENGER_FB_PAGE_TOKEN}

webhook:
  token: ${USS_MESSENGER_WEBHOOK_TOKEN}

uetgrade:
  server: http://localhost:8899

ws:
  uetgrade: ${uetgrade.server}/services/UetGrade