server:
  port: 8899

uet:
  grade:
    host: http://112.137.129.30/viewgrade
    term.code: 1
    education.type: 0
    account:
      username: ${UET_GRADE_USERNAME}
      password: ${UET_GRADE_PASSWORD}

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: none

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/uetgrade
    username: ${UET_GRADE_DB_USERNAME}
    password: ${UET_GRADE_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

messenger:
  server: ${USS_MESSENGER_SERVER}
ws:
  notifier: ${messenger.server}/services/Notifier

logging:
  level:
    net.bqc.uss: DEBUG
