server:
  port: 9999

fcm:
  api:
    url: https://fcm.googleapis.com/fcm/send
    key: ${USS_SERVER_FCM_API_KEY}
  topic:
    path: /topics/scholarships

uet:
  feed:
    url: https://uet.vnu.edu.vn/category/tin-tuc/tin-sinh-vien/feed

messenger:
  server: http://localhost:8888
ws:
  notifier: ${messenger.server}/services/Notifier